apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spotify-tracker

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml

# Add common labels to all resources
commonLabels:
  app: spotify-tracker
  managed-by: kustomize
